// Vault category definitions and field schemas

export const CATEGORIES = {
  bank_account: {
    label: 'Bank Accounts',
    icon: 'Landmark',
    fields: [
      { name: 'bankName', label: 'Bank Name', type: 'text', required: true },
      { name: 'accountNumber', label: 'Account Number', type: 'text', required: true },
      { name: 'accountType', label: 'Account Type', type: 'select', options: ['Savings', 'Current', 'Salary', 'NRI', 'Joint'] },
      { name: 'ifscCode', label: 'IFSC Code', type: 'text' },
      { name: 'branch', label: 'Branch', type: 'text' },
      { name: 'netBankingId', label: 'Net Banking User ID', type: 'text', sensitive: true },
      { name: 'netBankingPassword', label: 'Net Banking Password', type: 'password', sensitive: true },
      { name: 'upiId', label: 'UPI ID', type: 'text' },
      { name: 'mobileLinked', label: 'Linked Mobile Number', type: 'text' },
      { name: 'debitCardNumber', label: 'Debit Card Number', type: 'text', sensitive: true },
      { name: 'nomineeName', label: 'Bank Nominee', type: 'text' },
      { name: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },
  broker_demat: {
    label: 'Share Broker / Demat',
    icon: 'TrendingUp',
    fields: [
      { name: 'brokerName', label: 'Broker Name', type: 'text', required: true },
      { name: 'clientId', label: 'Client ID', type: 'text', required: true },
      { name: 'dematNumber', label: 'Demat Account Number', type: 'text' },
      { name: 'dpId', label: 'DP ID', type: 'text' },
      { name: 'loginId', label: 'Login ID', type: 'text', sensitive: true },
      { name: 'password', label: 'Password', type: 'password', sensitive: true },
      { name: 'pin', label: 'Trading PIN', type: 'password', sensitive: true },
      { name: 'linkedBank', label: 'Linked Bank Account', type: 'text' },
      { name: 'nomineeName', label: 'Nominee', type: 'text' },
      { name: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },
  mutual_fund: {
    label: 'Mutual Funds',
    icon: 'PieChart',
    fields: [
      { name: 'amcName', label: 'AMC Name', type: 'text', required: true },
      { name: 'folioNumber', label: 'Folio Number', type: 'text', required: true },
      { name: 'schemeName', label: 'Scheme Name', type: 'text' },
      { name: 'platform', label: 'Platform (CAMS/KFintech/App)', type: 'text' },
      { name: 'loginId', label: 'Login ID', type: 'text', sensitive: true },
      { name: 'password', label: 'Password', type: 'password', sensitive: true },
      { name: 'nomineeName', label: 'Nominee', type: 'text' },
      { name: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },
  insurance: {
    label: 'Insurance',
    icon: 'Shield',
    fields: [
      { name: 'provider', label: 'Insurance Provider', type: 'text', required: true },
      { name: 'policyNumber', label: 'Policy Number', type: 'text', required: true },
      { name: 'policyType', label: 'Type', type: 'select', options: ['Life', 'Health', 'Term', 'Vehicle', 'Home', 'Travel', 'ULIP'] },
      { name: 'sumAssured', label: 'Sum Assured (₹)', type: 'text' },
      { name: 'premium', label: 'Premium Amount (₹)', type: 'text' },
      { name: 'premiumFrequency', label: 'Premium Frequency', type: 'select', options: ['Monthly', 'Quarterly', 'Half-Yearly', 'Yearly'] },
      { name: 'startDate', label: 'Policy Start Date', type: 'date' },
      { name: 'maturityDate', label: 'Maturity Date', type: 'date' },
      { name: 'nomineeName', label: 'Nominee', type: 'text' },
      { name: 'loginId', label: 'Portal Login', type: 'text', sensitive: true },
      { name: 'password', label: 'Portal Password', type: 'password', sensitive: true },
      { name: 'agentName', label: 'Agent Name', type: 'text' },
      { name: 'agentPhone', label: 'Agent Phone', type: 'text' },
      { name: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },
  real_estate: {
    label: 'Real Estate',
    icon: 'Home',
    fields: [
      { name: 'propertyType', label: 'Property Type', type: 'select', options: ['House', 'Apartment', 'Land/Plot', 'Commercial', 'Farm Land'], required: true },
      { name: 'description', label: 'Description', type: 'text', required: true },
      { name: 'address', label: 'Full Address', type: 'textarea' },
      { name: 'area', label: 'Area (sq ft / acres)', type: 'text' },
      { name: 'registrationNumber', label: 'Registration Number', type: 'text' },
      { name: 'registrationDate', label: 'Registration Date', type: 'date' },
      { name: 'purchaseValue', label: 'Purchase Value (₹)', type: 'text' },
      { name: 'currentValue', label: 'Estimated Current Value (₹)', type: 'text' },
      { name: 'ownershipType', label: 'Ownership', type: 'select', options: ['Self', 'Joint', 'Family', 'Inherited'] },
      { name: 'coOwners', label: 'Co-owners', type: 'text' },
      { name: 'documentLocation', label: 'Document Storage Location', type: 'text' },
      { name: 'loanLinked', label: 'Loan Linked', type: 'text' },
      { name: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },
  gold: {
    label: 'Gold & Precious Metals',
    icon: 'Gem',
    fields: [
      { name: 'type', label: 'Type', type: 'select', options: ['Physical Gold', 'Gold Coins', 'Sovereign Gold Bond', 'Gold ETF', 'Silver', 'Platinum', 'Jewelry'], required: true },
      { name: 'description', label: 'Description', type: 'text', required: true },
      { name: 'weight', label: 'Weight (grams)', type: 'text' },
      { name: 'purity', label: 'Purity (e.g., 24K, 22K)', type: 'text' },
      { name: 'purchaseValue', label: 'Purchase Value (₹)', type: 'text' },
      { name: 'purchaseDate', label: 'Purchase Date', type: 'date' },
      { name: 'storageLocation', label: 'Storage Location', type: 'text' },
      { name: 'bankLocker', label: 'Bank Locker Details', type: 'text' },
      { name: 'invoiceNumber', label: 'Invoice/Certificate Number', type: 'text' },
      { name: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },
  epf_ppf_nps: {
    label: 'EPF / PPF / NPS',
    icon: 'Wallet',
    fields: [
      { name: 'type', label: 'Type', type: 'select', options: ['EPF', 'PPF', 'NPS', 'APY'], required: true },
      { name: 'accountNumber', label: 'Account / UAN Number', type: 'text', required: true },
      { name: 'employer', label: 'Employer (for EPF)', type: 'text' },
      { name: 'loginId', label: 'Portal Login ID', type: 'text', sensitive: true },
      { name: 'password', label: 'Portal Password', type: 'password', sensitive: true },
      { name: 'nomineeName', label: 'Nominee', type: 'text' },
      { name: 'linkedBank', label: 'Linked Bank Account', type: 'text' },
      { name: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },
  fixed_deposit: {
    label: 'Fixed Deposits & Bonds',
    icon: 'Banknote',
    fields: [
      { name: 'institution', label: 'Bank / Institution', type: 'text', required: true },
      { name: 'type', label: 'Type', type: 'select', options: ['FD', 'RD', 'Government Bond', 'Corporate Bond', 'Tax-saving FD'] },
      { name: 'accountNumber', label: 'FD / Bond Number', type: 'text', required: true },
      { name: 'principal', label: 'Principal Amount (₹)', type: 'text' },
      { name: 'interestRate', label: 'Interest Rate (%)', type: 'text' },
      { name: 'startDate', label: 'Start Date', type: 'date' },
      { name: 'maturityDate', label: 'Maturity Date', type: 'date' },
      { name: 'maturityAmount', label: 'Maturity Amount (₹)', type: 'text' },
      { name: 'nomineeName', label: 'Nominee', type: 'text' },
      { name: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },
  credit_card: {
    label: 'Credit Cards',
    icon: 'CreditCard',
    fields: [
      { name: 'bank', label: 'Bank / Issuer', type: 'text', required: true },
      { name: 'cardType', label: 'Card Type', type: 'text' },
      { name: 'cardNumber', label: 'Card Number (last 4 or full)', type: 'text', sensitive: true },
      { name: 'expiryDate', label: 'Expiry Date', type: 'text', sensitive: true },
      { name: 'creditLimit', label: 'Credit Limit (₹)', type: 'text' },
      { name: 'billingDate', label: 'Billing Date', type: 'text' },
      { name: 'loginId', label: 'Portal Login', type: 'text', sensitive: true },
      { name: 'password', label: 'Portal Password', type: 'password', sensitive: true },
      { name: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },
  loan: {
    label: 'Loans & Liabilities',
    icon: 'Receipt',
    fields: [
      { name: 'lender', label: 'Lender / Bank', type: 'text', required: true },
      { name: 'loanType', label: 'Loan Type', type: 'select', options: ['Home Loan', 'Personal Loan', 'Vehicle Loan', 'Education Loan', 'Gold Loan', 'Business Loan', 'Other'] },
      { name: 'loanAccountNumber', label: 'Loan Account Number', type: 'text', required: true },
      { name: 'sanctionedAmount', label: 'Sanctioned Amount (₹)', type: 'text' },
      { name: 'outstandingAmount', label: 'Outstanding Amount (₹)', type: 'text' },
      { name: 'emi', label: 'EMI Amount (₹)', type: 'text' },
      { name: 'interestRate', label: 'Interest Rate (%)', type: 'text' },
      { name: 'startDate', label: 'Loan Start Date', type: 'date' },
      { name: 'endDate', label: 'Loan End Date', type: 'date' },
      { name: 'linkedProperty', label: 'Linked Property / Asset', type: 'text' },
      { name: 'loginId', label: 'Portal Login', type: 'text', sensitive: true },
      { name: 'password', label: 'Portal Password', type: 'password', sensitive: true },
      { name: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },
  tax_record: {
    label: 'Tax Records',
    icon: 'FileText',
    fields: [
      { name: 'panNumber', label: 'PAN Number', type: 'text', required: true },
      { name: 'itrPortalLogin', label: 'ITR Portal Login', type: 'text', sensitive: true },
      { name: 'itrPortalPassword', label: 'ITR Portal Password', type: 'password', sensitive: true },
      { name: 'tanNumber', label: 'TAN Number', type: 'text' },
      { name: 'gstNumber', label: 'GST Number', type: 'text' },
      { name: 'caName', label: 'CA / Tax Consultant Name', type: 'text' },
      { name: 'caPhone', label: 'CA Phone', type: 'text' },
      { name: 'caEmail', label: 'CA Email', type: 'text' },
      { name: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },
  document: {
    label: 'Important Documents',
    icon: 'FolderLock',
    fields: [
      { name: 'documentType', label: 'Document Type', type: 'select', options: ['Aadhaar', 'Passport', 'Voter ID', 'Driving License', 'Will', 'Power of Attorney', 'Birth Certificate', 'Marriage Certificate', 'Other'], required: true },
      { name: 'documentNumber', label: 'Document Number', type: 'text', sensitive: true },
      { name: 'issuedBy', label: 'Issued By', type: 'text' },
      { name: 'issueDate', label: 'Issue Date', type: 'date' },
      { name: 'expiryDate', label: 'Expiry Date', type: 'date' },
      { name: 'storageLocation', label: 'Physical Storage Location', type: 'text' },
      { name: 'digilockerLinked', label: 'DigiLocker Linked', type: 'select', options: ['Yes', 'No'] },
      { name: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },
  digital_asset: {
    label: 'Digital Assets',
    icon: 'Globe',
    fields: [
      { name: 'type', label: 'Type', type: 'select', options: ['Email Account', 'Crypto Wallet', 'Domain Name', 'Social Media', 'Cloud Storage', 'Subscription', 'Other'], required: true },
      { name: 'platform', label: 'Platform / Service', type: 'text', required: true },
      { name: 'username', label: 'Username / Login', type: 'text', sensitive: true },
      { name: 'password', label: 'Password', type: 'password', sensitive: true },
      { name: 'recoveryEmail', label: 'Recovery Email', type: 'text' },
      { name: 'recoveryPhone', label: 'Recovery Phone', type: 'text' },
      { name: 'twoFactorMethod', label: '2FA Method', type: 'text' },
      { name: 'seedPhrase', label: 'Seed Phrase / Recovery Key', type: 'textarea', sensitive: true },
      { name: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },
  personal_note: {
    label: 'Personal Notes & Instructions',
    icon: 'Heart',
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'content', label: 'Content', type: 'textarea', required: true },
      { name: 'forWhom', label: 'Intended For', type: 'text' },
    ],
  },
};

export const CATEGORY_LIST = Object.entries(CATEGORIES).map(([key, val]) => ({
  key,
  ...val,
}));
